package com.neosoft.sportsclubmanagement.model;
// Generated Sep 22, 2017 12:01:42 PM by Hibernate Tools 5.1.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details")
public class UserDetails implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer udid;
	private User user;
	private String name;
	private String surname;
	private Date createdOn;
	private Date updatedOn;
	private Date dob;

	public UserDetails() {
	}

	public UserDetails(User user, String name, String surname, Date createdOn, Date updatedOn, Date dob) {
		this.user = user;
		this.name = name;
		this.surname = surname;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.dob = dob;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UDID", unique = true, nullable = false)
	public Integer getUdid() {
		return this.udid;
	}

	public void setUdid(Integer udid) {
		this.udid = udid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_UID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "NAME", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SURNAME", length = 20)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_ON", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_ON", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

}
