package com.neosoft.sportsclubmanagement.model;
// Generated Sep 22, 2017 12:01:42 PM by Hibernate Tools 5.1.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "user_roles")
public class UserRoles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer rid;
	private String role;
	private String description;
	private Set<User> users = new HashSet<User>(0);
	private Set<User> users_1 = new HashSet<User>(0);

	public UserRoles() {
	}

	public UserRoles(String role, String description, Set<User> users, Set<User> users_1) {
		this.role = role;
		this.description = description;
		this.users = users;
		this.users_1 = users_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RID", unique = true, nullable = false)
	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	@Column(name = "ROLE", length = 20)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<User> getUsers_1() {
		return this.users_1;
	}

	public void setUsers_1(Set<User> users_1) {
		this.users_1 = users_1;
	}

}
