package com.neosoft.sportsclubmanagement.model;
// Generated Sep 22, 2017 12:01:42 PM by Hibernate Tools 5.1.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserContacts generated by hbm2java
 */
@Entity
@Table(name = "user_contacts", uniqueConstraints = @UniqueConstraint(columnNames = "contacts_cid"))
public class UserContacts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private UserContactsId id;
	private User user;
	private UserContact userContact;

	public UserContacts() {
	}

	public UserContacts(UserContactsId id, User user, UserContact userContact) {
		this.id = id;
		this.user = user;
		this.userContact = userContact;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userUid", column = @Column(name = "user_uid", nullable = false)),
			@AttributeOverride(name = "contactsCid", column = @Column(name = "contacts_cid", unique = true, nullable = false)) })
	public UserContactsId getId() {
		return this.id;
	}

	public void setId(UserContactsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_uid", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contacts_cid", unique = true, nullable = false, insertable = false, updatable = false)
	public UserContact getUserContact() {
		return this.userContact;
	}

	public void setUserContact(UserContact userContact) {
		this.userContact = userContact;
	}

}
